Add-Type -AssemblyName System.Drawing
$img = [System.Drawing.Image]::FromFile("c:\Projetos\WII\logo.png")
$cropX = [int]($img.Width * 0.15)
$cropY = [int]($img.Height * 0.12)
$cropW = [int]($img.Width * 0.70)
$cropH = [int]($img.Height * 0.65)
$rect = New-Object System.Drawing.Rectangle($cropX, $cropY, $cropW, $cropH)
$bmp = New-Object System.Drawing.Bitmap($cropW, $cropH)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.DrawImage($img, (New-Object System.Drawing.Rectangle(0, 0, $cropW, $cropH)), $rect, [System.Drawing.GraphicsUnit]::Pixel)
$g.Dispose()
$img.Dispose()
$bmp.Save("c:\Projetos\WII\logo_cropped.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp.Dispose()
